### ISSUE TITLE
How to know which Arweave blocks to target when running the program?

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/Mirror.XYZ-Scraper#1]
In the `README` for this project there's the instruction:

> To gather all Mirror.XYZ publications between two Arweave blocks and output to a JSON, run `node runPipeline <startBlock> <endBlock> '<desiredPath>.json'`.

Which makes perfect sense. What's the best way to figure out which values of `<startBlock>` and `<endBlock>` to input?

**Comment by nathankoerschner** [comment]
See here:
https://github.com/DiamondDAO/Mirror.XYZ-Scraper/blob/1468ce1a9e30740abcfebf1de8455305d0fc426f/pipeline_parts/arweave.js#L78

For the end block, can reference slightly beyond the current areweave block
